import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data1 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik0.csv")
data2 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik1.csv")
data3 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik2.csv")
data4 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik3.csv")
data5 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik4.csv")
data6 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik5.csv")
data7 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik6.csv")
data8 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik7.csv")
data9 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik8.csv")
data10 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik9.csv")
data11 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik10.csv")
data12 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik11.csv")
data13 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik12.csv")
data14 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik13.csv")
data15 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik14.csv")
data16 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik15.csv")
data17 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik16.csv")
data18 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik17.csv")
data19 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik18.csv")
data20 = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\plik19.csv")

centre = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\centre.csv")
path = pd.read_csv("E:\Praca inżynierska\simulation\controllers\ctrl_1\path.csv")

x1 = np.array(data1["x"])
y1 = np.array(data1["y"])
x2 = np.array(data2["x"])
y2 = np.array(data2["y"])
x3 = np.array(data3["x"])
y3 = np.array(data3["y"])
x4 = np.array(data4["x"])
y4 = np.array(data4["y"])
x5 = np.array(data5["x"])
y5 = np.array(data5["y"])
x6 = np.array(data6["x"])
y6 = np.array(data6["y"])
x7 = np.array(data7["x"])
y7 = np.array(data7["y"])
x8 = np.array(data8["x"])
y8 = np.array(data8["y"])
x9 = np.array(data9["x"])
y9 = np.array(data9["y"])
x10 = np.array(data10["x"])
y10 = np.array(data10["y"])
x11 = np.array(data11["x"])
y11 = np.array(data11["y"])
x12 = np.array(data12["x"])
y12 = np.array(data12["y"])
x13 = np.array(data13["x"])
y13 = np.array(data13["y"])
x14 = np.array(data14["x"])
y14 = np.array(data14["y"])
x15 = np.array(data15["x"])
y15 = np.array(data15["y"])
x16 = np.array(data16["x"])
y16 = np.array(data16["y"])
x17 = np.array(data17["x"])
y17 = np.array(data17["y"])
x18 = np.array(data18["x"])
y18 = np.array(data18["y"])
x19 = np.array(data19["x"])
y19 = np.array(data19["y"])
x20 = np.array(data20["x"])
y20 = np.array(data20["y"])
path_x = np.array(path["x"])
path_y = np.array(path["y"])
centre_x = np.array(centre["x"])
centre_y = np.array(centre["y"])
# i = np.array(data.index)
fig = plt.figure()
ax1 = fig.add_subplot()

ax1.scatter(x1, y1, c="c", s=20)
ax1.scatter(x2, y2, c="m",s=20)
ax1.scatter(x3, y3, c="y",s=20)
ax1.scatter(x4, y4, c="g",s=20)
ax1.scatter(x5, y5, c="k",s=20)
ax1.scatter(x6, y6, c="c",s=20)
ax1.scatter(x7, y7, c="m",s=20)
ax1.scatter(x8, y8, c="y",s=20)
ax1.scatter(x9, y9, c="g",s=20)
ax1.scatter(x10, y10, c="k",s=20)
ax1.scatter(x11, y11, c="c",s=20)
ax1.scatter(x12, y12, c="m",s=20)
ax1.scatter(x13, y13, c="y",s=20)
ax1.scatter(x14, y14, c="g",s=20)
ax1.scatter(x15, y15, c="k",s=20)
ax1.scatter(x16, y16, c="c",s=20)
ax1.scatter(x17, y17, c="m",s=20)
ax1.scatter(x18, y18, c="y",s=20)
ax1.scatter(x19, y19, c="g",s=20)
ax1.scatter(x20, y20, c="k",s=20)
circle1 = plt.Circle((path_x[0], path_y[0]), 70, color='b', fill=False)
circle2 = plt.Circle((path_x[-1], path_y[-1]), 70, color='g', fill=False)
ax1.add_patch(circle1)
ax1.add_patch(circle2)

ax1.scatter(centre_x, centre_y, s=60, c='r', marker="o")


ax1.plot(path_x, path_y)
# ax1.legend(['Przeszkoda 1', 'Przeszkoda 2','Przeszkoda 3',"Położenie początkowe", "Położenie końcowe", "Środki przeszkód", "Ścieżka robota"], fontsize=18)
# plt.title("Droga przebyta przez robota oraz wykryte obiekty", fontsize=40)
ax1.grid()
# plt.axis([-600, 300, -100, 1100])
# ax1.colorbar()

plt.show()